verbose: True
redis:
  port: 6379
qth: 
  heure:
    latitude:
    longitude:
    maidenhaid: 
  merchtem:
    latitude:
    longitude:
    maidenhaid: 
  lombardsijde:
    latitude:
    longitude:
    maidenhaid:
  opwijk:
    latitude:
    longitude:
    maidenhaid:
qsl:
  OO5CARE:
    station: OO5CARE
    operator: ON3URE
    logbook: oo5care
  ON4AOW:
    station: ON4AOW
    operator: ON3URE
    logbook: on4aow
  ON3URE/P:
    station: ON3URE
    operator: ON3URE
    logbook: on3ure
  ON3URE/A:
    station: ON3URE
    operator: ON3URE
    logbook: on3ure
  ON3URE:
    station: ON3URE
    operator: ON3URE
    logbook: on3ure
qrz.com:
  username: ""
  password: ""
email:
  exec: "pb mailto:"
qso:
  exec: "qso "
qsl:
  exec: "qso --qsl "
